services:
  - type: web
    name: notivo-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist -l 3000
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: "18"
    routes:
      - path: /
        destination: /index.html
